# netlify.toml
[build]
  # Run prisma generate, migrate, seed production DB, then build
  command = "npx prisma generate && npx prisma migrate deploy && npm run db:seed:prod && node netlify-build.js"
  # Directory containing the built site (relative to root)
  publish = ".next"

[build.environment]
[build.environment]
  # Set Node.js version (Optional but recommended - use a version supported by Netlify)
  NODE_VERSION = "20"
  # Ensure Prisma CLI is available during build (it's in devDependencies)
  # Disable static generation entirely
  NEXT_DISABLE_STATIC_GENERATION = "true"
  # Skip static generation in the Next.js plugin
  NEXT_USE_NETLIFY_EDGE = "true"

# Configure the Next.js plugin without any inputs
[[plugins]]
  package = "@netlify/plugin-nextjs"