[build]
  command = "PRISMA_MIGRATE_TIMEOUT=30000 prisma generate && (prisma migrate deploy || true) && next build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["bcrypt"]

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Authorization"

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true
