[build]
  command = "PRISMA_MIGRATE_TIMEOUT=30000 prisma generate && (prisma migrate deploy || true) && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["bcrypt", "@prisma/client", "prisma"]
  included_files = ["prisma/**", ".env*"]
  timeout = 30

[functions.memory]
  amount = 1024

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Authorization, Cookie"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Expose-Headers = "Set-Cookie"

[[redirects]]
  from = "/api/locations*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Cookie"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Expose-Headers = "Set-Cookie"

[[redirects]]
  from = "/management-portal-8f7d3e2a1c/*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true

[[redirects]]
  from = "/secure-access-9b1c3f5d7e"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
