[[redirects]]
  from = "https://*.netlify.app/*"
  to = "https://www.bookshuttles.com/:splat"
  status = 301
  force = true

[build]
  command = "PRISMA_MIGRATE_TIMEOUT=30000 prisma generate && (prisma migrate deploy || true) && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["bcrypt", "@prisma/client", "prisma"]
  included_files = ["prisma/**", ".env*"]
  # Removed global timeout setting here

# Apply timeout specifically to all functions
[functions."*"]
  timeout = 26 # Increase timeout for functions (e.g., OpenAI calls)

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/management-portal-8f7d3e2a1c/*"
  to = "/admin/:splat" # Let Next.js handle the internal routing after Netlify rewrite
  status = 200
  force = true


# Fallback rule to ensure all paths are served
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Note: Consider if you need specific headers for this admin path

[[redirects]]
  from = "/secure-access-9b1c3f5d7e"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true
