[[redirects]]
  from = "https://*.netlify.app/*"
  to = "https://www.bookshuttles.com/:splat"
  status = 301
  force = true

[build]
  command = "PRISMA_MIGRATE_TIMEOUT=30000 prisma generate && (prisma migrate deploy || true) && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["bcrypt", "@prisma/client", "prisma"]
  included_files = ["prisma/**", ".env*", "public/**/*"]
  maxDuration = 30

[functions.api]
  memory = 1024

[functions.next_server]
  included_files = ["public/**/*", "prisma/**"]
  memory = 1024
  maxDuration = 30

[[headers]]
  for = "/routes/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Timing-Allow-Origin = "*"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/routes/*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true
  conditions = { Function = "next_server" }

[[redirects]]
  from = "/management-portal-8f7d3e2a1c/*"
  to = "/admin/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/secure-access-9b1c3f5d7e"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true
