# netlify.toml
[build]
  # Run prisma commands in sequence to ensure proper database setup
  command = "npm install && npm run postinstall && echo 'Creating .env file for build...' && touch .env && npx prisma generate && npx prisma migrate deploy && npm run db:seed:prod && node netlify-reset-password.js && node netlify-build.js"
  # Directory containing the built site (relative to root)
  publish = ".next"

# Development configuration
[dev]
  framework = "nextjs"

[build.environment]
  # Set Node.js version to match Next.js requirements
  NODE_VERSION = "20.11.1"
  # Ensure proper environment for production
  NODE_ENV = "production"
  # Auth-related environment variables
  NEXTAUTH_URL = "https://findshuttles.netlify.app"
  # Session configuration for Netlify
  NEXT_PUBLIC_COOKIE_SECURE = "true"
  NEXTAUTH_COOKIE_DOMAIN = "findshuttles.netlify.app"
  # Disable static generation entirely
  NEXT_DISABLE_STATIC_GENERATION = "true"
  # Skip static generation in the Next.js plugin
  NEXT_USE_NETLIFY_EDGE = "true"
  # JWT Default Secret - will be overridden by environment secret
  JWT_SECRET = "fallback-secret-for-netlify-testing"
  # Auth0 configuration - these will be replaced by actual values in Netlify dashboard
  AUTH0_BASE_URL = "https://findshuttles.netlify.app"

# Configure the Next.js plugin without any inputs
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Emergency admin bypass access
[[redirects]]
  from = "/emergency-admin"
  to = "/admin-bypass"
  status = 200
  force = true

# Direct admin access - this provides a more reliable bypass
[[redirects]]
  from = "/direct-admin"
  to = "/admin-bypass"
  status = 200
  force = true
  
# System access - reliable direct authentication system
[[redirects]]
  from = "/system-access"
  to = "/system-access"
  status = 200
  force = true
  
# Auth0 API endpoints
[[redirects]]
  from = "/api/auth/*"
  to = "/api/auth/:splat"
  status = 200
  force = true

# System access API endpoints
[[redirects]]
  from = "/api/system-auth/*"
  to = "/api/system-auth/:splat"
  status = 200
  force = true
  
# Note: We can't redirect /.netlify/* paths as they're reserved by Netlify
# The Netlify Identity API is handled automatically by Netlify

# Auth0 login specific redirects will be handled by Auth0 itself
# No need for additional redirects as Auth0 handles callback URLs directly
