import { ImageResponse } from '@vercel/og';
import { NextRequest } from 'next/server';
import React from 'react'; // Explicitly import React
// Removed fs/promises and path imports as they are not available in edge runtime

export const runtime = "edge";

// Base64 encoded font data (Inter-Regular.otf)
const interRegularOtfBase64 = "T1RUTwAMAIAAAwBAQkZTSUYyAAAFKAAAF1gAAAZgR0RFRgAABZgAAAGIAAAKNERUZYQAAAZgAAABHAAAACRPU1YyYn7w/wAAAVgAAABgR01YWFQAAAHEAAABAAAACjxoZWFk/jAAwAAAANwAAAA2aGhlYQYgB+AAAAHoAAAAJGhtdHggGgAAAAHIAAAAEGxvY2EAZgAAAAHMAAAACm1heHACHwAAAAHkAAAAIG5hbWUg/1sAAAHwAAACUnBvc3QAAAUAAAAFoAAAACAAAwAAAAIAAZUAAQAAAAAAAwAAAAMAAAAAAADAAAAAwAAAYAAAAAEAAAAAxWGbMJBfDzz1ABsLAAAAAADYfWYlAAAAANh9Zmn34PvEEioMAAAAAAYAAgAAAAAAAAABAAAKlP1sAAATQPfg+mASKgABAAAAAAAAAAAAAAAAAAAJKQrwAPgAAAAAAxgAAAMYAAADGAAAAxgAAAdwAEgHcABIB3AASAdwAEgHcABIB3AASAdwAEgHcABIB3AASAdwAEgHcABIB3AASAdwAEgHcABIB3AASAdwAEgHcABIB3AASAdwAEgHcABIB3AASAdwADQHcABIB3AASAdwAEgHcABIB3AASAdwAEgHcABIB3AASAdwAEgHcABIB3AASAdwAEgHcP7IB3D/MAdw/0QHcP8UB3D/5Adw/9gHcABIB3AASAdwAEgHcABIB3AASAdwAEgHcABIB3AASAdwAEgHcABIB3D+yAdw/zAHcP9EB3D/FAdw/+QHcP/YB3AASAdwAEgK5ABICuQASArkAEgK5ABIBygA+AcoAPgHKAD4BygA+AfEAFgI1ACIBygA+AcoAPgIAACoCHwAqAgAAKgIAACoCAAAqAgAAKgIAACoCAAAqAgAAKgIAACoCAAAqAgAAKgIAACYCAAAqAfoAPgJpACIB+gA+AfoAPgH6AD4B+gA+AfoAPgH6AD4B+j/vA3cAPgN3AD4BpQA+AaUAPgGlAD4BpQA+AaUAPgGlAD4BpQA+AaUAPgGlAD4BpQA+AaUAJwGlAD4BpQA+AaUAPgGlAD4BpQA+AaUAPgGlAD4BpQA+AaUAPgGlAD4BpQA+AaU/9wGlAD4BpQA+AaUAPgGlAD4BoQAsAaUAPgHmABkB/gAZAfkAGQKIABkCbgAZAmkAGQJ1ABkCHQAZAgkAGQGlAD4BpQA+AaUAPgGlAD4BnQA+AZ0/9AGdAD4BnQAsAgsAKgILACoCIAAqAgsAKgILACoCCwAqAgsAKgILACoCCwAqAgsAKgIQACoCEAAqAiAAKgIQACoCEAAqAhAAKgIQACoCEAAqAhAAKgIQACoCCQA+AgkAPgIJAD4CCQA+AgkAPgIJAD4CCQA+AgkAPgIjACICCQA+AiAAPgIrAD4CtgA+AxAAPgIJAD4CXwAyAncAMgJyADIDAQAyAucAMgLiADIC7gAyAroAMgK9ADIClgAyAoIAMgIJAD4CXgAZAnIAMgMBADIC5wAyAuIAMgLuADICugAyAr0AMgIJAD4AugA+ALo/7QC6P+0Auj/vALo/9gC6P/YAugA+ALo/8QE4ACEAuj/oALo/9gC6AAYAugAzALo/8QC6P6wAuj/2ALoAPgC6ADMAugA+ANYABAC6P+0BHAAyARcAMgGmADIBjAAyAYcAMgGTADIBXwAyAWIAMgC6P/YAuj/oATsAMgEnADIAugA+ALo/7QE4ACIBOAAiATgAIgE4ACIBOAAiATgAIgE4ACIBOAAiATgAIQE4ACIBOAAiATgAIgE4ACIBOAAiATg/6wE4ACIBOAAiATgAIgGmACIBoQAiAjAAIgIWACICEQAiAh0AIgHpACIB7AAiATgAIgE4ACIBxQAiAbEAIgE4ACIBOAAiAX4AHQF+AB0BfgAdAX4AHQF+AB0BywA+AcsAPgHLAD4BywA+AcsAPgHLAD4CDQAGAfYAPgHZAD4BywA+AYwAPgGMAD4BjAA+AYwAPgGMAD4BjD/oAYwAPgGMAD4BjAAPAYw/7wIzAD4CggA+AoIAPgKCAD4CggA+AoIAPgKCAD4CggA+AoIAPgISAD4CEgA+AhIAPgISAD4CEgA+AhIAPgISAD4CEgA+AhIAPgISAD4CFT/3AhIAPgISAD4CEgA+AhIAPgISAD4CEgA+AhIAPgISAD4CEgA+Aq8APgIYACoCGAAqAhgAKgIYACoCIQAqAhgAKgIYACoCGAAqAhgAKgIYACoCGAAqAhgAKgIYACoCGAAqAhgAKgIYACoCGAAqAhgAKgIYACoCGAAqAhgAKgIYACoCGAAqAhgAKgIYACoCGAAqAhgAKgIYACoCGAAqAhgAKgIYACoCIQAqAiEAKgIhACoCIQAqAiEAKgIYACoCGAAqAiY//AI+P/wCVgAZAsg//AKkP/ICiz/8ApM//AJdP/wCGAAqAis//AIYACoCGAAqAhgAKgIYACoCGAAqAp8AKgG/AD4BvwA+Ab8APgG/AD4CKgAiAb8APgIWACECGAAqAcIAPgHCAD4BwgA+AcIAPgHCAC0BwgA+AcIAPgHCAD4BwgA+AcIAPgHCAD4B4QA+AcgACAHBACgBwQAoAcEAKAHBACgBwQAoAcEAKAHBACgBwQAoAcEAKAHBACgBwQAoAcEAKAHBACgB4AA+AcQAIgHEACIBxAAiAcQAIgHEACIBxAAiAcQAIgHEACIB4AAiAcQAIgHEACIBxAAiAgoAPgJhAD4CCgA+AgoAPgIKAD4CCgA+AgoAPgIKAD4CCgA+AgoAPgIKAD4CCgA+AgoAPgIKAD4CCgA+AgoAPgIKAD4CCgA+AgoAPgIKAD4CCgA+AgoAPgIKAD4CCgA+AgoAPgIKAD4CYQA+AmEAPgJhAD4CYQA+AmEAPgIKP/4B3AASAdwAEgHcABICnAAPApwADwKcAA8CnAAPApwADwKcAA8CnAAPAcQAEwHEABMBxAATAcQAEwHEABMBxAATAdQAEgHxABMB1AASAdQAEgHUABIB1AASAdQAEgHUABIB1AASAdQAEgHUABIB1gACAdQAEgI/ABIB1AASAj4AEwKpABMCzgASAp0AEgHUABIB1AASAk4AEwJHP/cBuAAqAbgAKgG4ACoBuAAqAbgAKgG4ACoBuAAqAbgAKgG4ACoBuAAqAbgAKgGNACQBjQAkAY0AJAGNACQBjQAkAY0AJAGNACQBjQAkAY0AJAGNACQBjQAkAY0AJAGNACQBjQAkAY0AJAGNABwBjQAkAY0AJAGNACQBjQAkAY0AJAGNACQBjT/sAY0AJAGNACQBjQAkAY0AJAGNACQBjQAkAY0AJAGNACQBjQA2AY0AJAGNACQBjQAkAosAJAKLACQCiwAkAosAJAG1AD4BtT/uAbUAPgGtADYBtQA+AbUAPgG1AD4BiQAkAYkAJAGuACQBiT/7AYkAJAGJACQBiQAkAYkAJAGJACQBiQAkAYkAJAGJACQBtQAkAbUAJAGtACQBsQAkAbUAJAH6ACQB4QAkAbUAJAG1ACQBtQAkAbUAJAG1ACQC6QAkAukAJAMWACQCoQAkAbUAJAGaACQBmgAkAZoAJAGaACQBmgAkAZoAJAGaACQBmgAkAZoAJAGaACQBmgAkAZoAHQGaACQBmgAkAZoAJAGaACQBmgAkAZoAJAGaACQBmgAkAZoAJAGaACQBmgAkAZo/7QGaACQBmgAkAZoAJAGaACQBmgAkAZoAJAGaACQBmgAkAP4AEgDtABIA/gBQAP4AEgJHABIBrQAkAbAAJAGtACQBrQAkAa0AJAGtACQBrQAkAa0AJAGtACQBrQAkAaAANgGgADYBoD/mAaA/5gGcADYBnAA2ApoANgGgADYB0wAeAd8AHgGgP+YBoD/oAaA/6AGgACoBoAA2AaA/5AGgADYBoAA2AaAANgCnACoApwA2AKc/5ACnP+QAxD/5AKc/7QCnP+0Apz/mAKc/7QCnADYApz/oAKc/3wCnP+0AqD/7AKg/+wCnP+gApz+jAKc/7QCnADYApwAqAKcAKgCnP/cApz/lAKc/5QCnP+UApwAqAKc/5AFOACoApz/3APQ/9wD0P/cApz/nAKc/5wCnP/cApz/3AU4ANgF/ADYBdwA2AX8ANgF/P+gBfwA2AX8ANgF/ADYBfwAKAKcANgCnP/8Apz/mANYAAgC8ADYBJwAQAPE/6ADeADYApwA2AKcAGADOADYApwAqAKc/3gCnP98Apz/oALYANgC2P/8Atj/mALY/6gEnABAA3gA2ALYANgC2AC0AzgA2ALYANgC2P94Atj/0ALY//QC6AD4CZAA2AmQANgJkADYCZAA2AmQANgJkADYCZAA2AZwANgGcADYBmQA2AZwANgIaADYBqD/3AZwANgGcADYBnAA2AZwANgGcADYBnAA2AZwANgGcADYBnAA2AkMANgGkACQBpAAkAaQAJAGkACQBpQAkAaQAJAGkACQBpAAkAaQAJAGkACQBpAAkAaQAJAGkACQBpAAkAaQAIQGkACQBpAAkAaQAJAGkACQBpAAkAaQAJAGkACQBpAAkAaQAJAGkACQBpAAkAaQAJAGkP/EBpAAkAaQAJAGkACQBpQAkAaUAJAGlACQBpQAkAaUAJAGkACQBpAAkAaQAJAGkACQBpAAkAaQAJAGkACQBpAAkAaQAJAGkACQBpAAkAaQAJAGkACQBpAAkArkAJANDACQBrQA2Aa0ANgGtADYBrQA2Aa0ANgGtADYBrQAkAcwAJAHCACQCJQAqAQ4ANgEOADYBDj/mAQ4ABgEjAAYA0wASANcANgEOADYBDgA2AQ4AFwEOACUBDj/gAQ4ANgEOADYBDgApAQ4AHAEOP94BBgA2AQYANgEGP+YBBgA2AQYANgEGABcBBgAlAQY/4AEGADIBBgA2AQYAKQEGABwBBj/eAXAAJQFwACUBcAAlAXAAJQFwACUBcAAlAXAAJQFwACUBcAAlAXAAJQFwACUBcAAlAXAAJQFwACUBcAAjAa0APgG8AD4BAAAWAQIAFgEEABYBVQAWAj4AFgEAABwBAAAWAQAAFgEOABYBAAAWAQAAFgEAABYBAAARAQAAFgEAP/4BmQA2AZkANgGZADYBtgA2AbYANgGxAAABmQA2AZkANgGZADYBmQA2AZkANgGZADYBmQA2AZkANgGZADYBmQA2AZkANgGZADYBmQA2AZkAHAGZADYBmQA2AZkANgGZADYBmQA2AZkANgGZADYBmQA2AbYANgG2ADYBtgA2AbYANgG2ADYBiAAYAYgAGAGIABgBiAAYAjwAGAI8ABgCPAAUAjwAGAI8ABgCPAAYAjwAGAI8ABgCPAAYAXwAHgF8AB4BfAAeAXwAHgGmAB4BiAAYAYgAGAGtABgBiAAYAYgAGAGIABgBiAAYAYgAGAGIABgBiAAYAYgAGAGIABgBiAAYAYgAGAGIABgBiAAYAYgAGAGIABgBiAAYAX0AKwF9ACsBfAAoAXsAKAGkACsBfQArAX0AKwF9ACsBfQArAX0AKwF9ACsBsQArAbwAOgGVAD4B3AASAhgAKgF8ABwB/AA/AbwALgIQACQCJAA+AhgAKgI9P/ICGj/yAjI/8gJKAA8CvD/yAqI/8gKdP/ICqT/yAnU/8gJ4P/ICUT/yAjI/8gJKAA8CvD/yAqI/8gKdP/ICqT/yAnU/8gJ4P/ICGAAqAhgAKgHSACACET/4AdIAIAG8AAcB0AA+AZUAPgGVP+8CEQASApwAEwKcABMBwAA0AccAPgHPAD4B3gA+AfYAEgIYACoB+gA+AbcAEgItACoCEQA+AnsAIgH3AEMB9wBDAfwAQwH3AD4CegAiAp4APgKyAD4CPAAiAlYAPgHMAD4C+gAOAxsAPgHYACoCyAA+AcIAFQG2AD4C/AArAdQAKgI8ADkCPAAsAecAJAG6AC0B7QASAjkAIgGYACQBrQA2AcMAJAHDACQBwwAkAcMAJAHDACQBwwAkAcMAJAHDACQBwwAkAcMAJAHDACQBwwAkAcMAJAHDACQBwwAkAcMAJAHDACQBwwAkAcMAJAHDACQBwwAkAcMAJAHDACQBwwAkAcMAJAHDACQBoQA2AXgAGAF8ABgBfwAkAX8AJAGMACQBfAAjAX8AIAGMACAB/AAgAX8AJAF/ACQBfwAkAX8AJAF/ACQBfwAkAX8AJAFwACIBnAA2AZwANgGcADYBnAA2AZwANgGcADYBnAA2AZwANgGcADYBnAA2AZwANgGcADYBnAA2AZwANgGcADYBnAA2AZwANgGcADYBnAA2AZwANgGcADYBnAA2AZwANgGcADYBfAAfALsANAC7P8UAuwA0ALs/1QC7ADAAuwAkALs/5QC7P+IAuwAEALs/8QC7P/gAuz/vALs//QC7P+oAuz/cALs/2gC7P9YAuz/aAZwAGAF8AC0BvAAZAZIAMgGSADIBkgAyAZI/4QF7ACQBvAApAUwACgGcADYBnAA2AZwANgGcADYBnAA2AZwANgGcADYBnAA2AZwANgGcADYBnAA2AZwANgGcADYBnAA2AZwANgGcADYBnAA2AZwANgIDACQB7AAkAg4ANgI8ACYCPAAmAjwAJgI8ACYCPAAmAjwAJgI8ACYCPAAmAjwAJgI8ACYCPAAmAjwAJgI8ACYCPAAmAjwAJgI8ACYCPAAmAjwAJgI8ACYCPAAmAjwAJgI8ACYCPAAmAjwAJgI8ACYCPAAmAjwAJgGjABgBnwAkAYsANgFDADYBRAA2AUM/1AG3AA0CRgAeAkYAHgFcAB4BpAA2Ac4ANgF6ADYBmgA2AZ0ANgGYADYB7gAgAZ8AFAHJABQBxAAUAhAANgI6ADYBmgA2Ab4ANgH6ADYBmgA2AcQANgGaADYBeAAgAd8AJAF8AB4BfAAeAb8ANgGaADYBlAA2AbkANgGUADYCPwA2AmIANgGGADYBzQASAhAANgGaAAcBmgAHAooAIAJ5ADYBfQAkAjwAGgGLAB0BfAA2AokANgF8AAsBvAAlAfgAIAIBABIBugAtAakAGAHBACgBiQAkAYIACgG8ACwBEAAKAZ8AIgHrABoB1AASAXwAFAHEACIDEgA+Af4AIwHyABICnAAPAccALAHcABIBuwAmAh4AEAILACoCAAAqAgAAKgIAACoBxAAiA3wAGAJZADYCNwA+AfwANAMRAD4B/AA0AZ0/7wG4ACoBNwArAaoANQGqADUBwAA0AcQAKQGsADYBpAAXAbcALQGSACIBsgAqgbcALQG4ACoBRwArAboALQHEACkBlAAoAZQAKQHIADIByAB1AcgARAHIADgByAArAcgAQwHIADUByAA9AcgANYHIADUByAAyAcgAagHIADUByAArAcgAQgHIAEMBwgAkAMQANQGIADUAxAA1AikANQFlABwCygAcAikAHAFlACMBZQAcAWUAIwD/AEsA/wAhAP8AUwD/AFMA/wAYAP8AGAD/ABoA/wAYApMAIgD/AEsA/wAhAP8AUwD/ABgA/wAaAP8AGAKTACIBvAAMAf0AKQD7ABAA5gBaALsAQgD8ABYBRAAyAUQAMgFgAAABvgAAAsAAAALAAAABQAAyAUAAMgFAAEQBQABPgUQAMgFgAAABvgAAAsAAAAFAADIBQAAyAUgARAFAAE+AjAAiAIwACwCcAAsAnAAyARwAMgEMACIBDAALAQwACwCMAAsAmwAjAR0AIwGfACMCIQAjAJsAIwEdACMBnwAjAKgAMQEPADEAxQAvAMIANAJCADQBggA0AMIANADCADQAxQAvAMIALADCADQAwgA0AMIALQD8AC8A/AAvAXwALwF8AC8BxABBAcQAQQHEAEEBxABBAcQAUgHEAFIBxABCAcQAQgHEAEIBxABCAcQAQQHEADMBxAAygcQAQQHEAEEBxABBAcQAQQHEAFIBxABSAcQAQgHEAEIBxABCAcQAQgHEAEEBxAAzAcQAMoF8AC8AxAA1AMQANQDCAC8BPj//AbwANAF8ABQBSgAcAWAAJwFgACcCPAAqAawAHAGkgBwB6AAcAgQAIAGuACABuIAgAUAALQE8AC8BPAAnAHwAGgE8ADABpgAmAYQAJAI8ACoCjwAkAbwAOAG8ABwB/ABAAMQ/5AG8ABoB4gAgAYAAHAELABUBJQAlAQ4AFQElABYBFAAVAK8AEAEjABYBHQAhAHgAHgB5P/YBBAAhAHcAIQGhACEBHAAhARoAFQEhACEBIQAWAL8AIQD+ABUAsQAOARsAIQELAA0BhQANAQMAEAELAA0BAwAdATYAGwDUABsBKAAhAS8AHgEzABoBJAAhASsAGwERABUBLQAaASsAHACyAC8AsgASALIAM4CyAAoBNQAsATUALAE1ADQBCwAVASUAJQEOABUBJQAWARQAFQCvABABIwAWAR0AIQB4AB4AeT/2AQQAIQB3ACEBoQAhARwAIQEaABUBIQAhASEAFgC/ACEA/gAVALEADgEbACEBCwANAYUADQEDABABCwANAQMAHQE2ABsA1AAbASgAIQEvAB4BMwAaASQAIQErABsBEQAVAS0AGgErABwAsgAvALIAEgCyADOAsgAKATUALAE1ACwBNQA0ARoAFwDBABgBDwAdARIAGgEWABcBCgAdAQ8AFwD3ABIBEwAXAQ8AGADBP5QBGgAXAMEAGAEPAB0BEgAaARYAFwEKAB0BDwAXAPcAEgETABcBDwAYARoAKAEaACgBGQAuAKUAKgClABABGgAXAMEAGAEPAB0BEgAaARYAFwEKAB0BDwAXAPcAEgETABcBDwAYARoAKAEaACgBGQAuAKUAKgClABABGgAXAMEAGAEPAB0BEgAaARYAFwEKAB0BDwAXAPcAEgETABcBDwAYAowAGAKUABgCawAYApkAGgK4AB0BjAAXApMAEgKQABgCvAAdAr4AGgI8ADsC4AA7A30AOwLwABUC6gAVAukAFQLaABUCvAAVAv4APgFeAG4BBAAhAV4AbgC8ADgBoABgAUAANAFgADUBPAApATwANwE8ADcAqAAqANwAEwFAADQBfAAzALwAPAC8ACAAAAAmAAA/ZgAAPwcAAD7VAAA+rQAAPsAAAD7DAAA+zgAAPs4AAD8XAAA+xAAAPssAAD7WAAA/DQAAPtQAAD96AAA+5QAAPwwAAD7MAAA+zgAAPwYAAD8KAAA+ogAAPtQAAD6UAAA+wQGAAAADAAAAAWAAAALAAAAA6wAAALAAAAB1AAABpgAAAMQAAACNAAAAgAAAAAAAAAKgAEWDsABFgqAAWAOwAFgCoACVgqAAi4KgAIuCoACVg7AARYTQAEWCoABvgqAAcAKgAHACoABFg7AARYKgAFgDsABYA7AARYTQAEWCbABMAmwAiQKEAEICxgAjAsYAIwKEACIAgAAAAAA+lwE8ADAAAD8OAAA+uwE+P/8AugA+AbwALwM4AC0AAD7KAAA+yQC8ACcAvAAxAXwAIAHJADEAAD7BAAA/AQAAPtwAAD7cAAA+1wAAPrQAAD7pAAA+0gAAPqUAAD6lAAA+zgAAPxMAAD7ZAAA+5QAAPyAAAD7BAAA/HwAAPvkBxAATAt0ALQHLAD4B/QA2ATwADQE8ADIB/AAoArwALgJ8ADoAAD8MAAA+pQF8ACkAAD6tATwAMgAAPtQAAD7KApcAPgE8ABYBPAAWALwACgF8AAoB/AAtAbwAHAIAACoCAAAiAXwAKgHMACYBfAAgAbwAPAG8ADEAAD9CAjwAGgAAPsUBfAAgAXwAIAF8ACABfAAgAXwAHwF8ACABzAA+AbwAEgC8ACsAvAArAHwAGwG8AD0B9wAHAbwAOAC8ACgBZAAnAbwAJgG8ACYBfAA5ATwAKADAAAAAAD5mAMQANQG8ADwAAD7OAPwAKgAAPuwAAD60AAA/DwAAPvwAAD7mAAA+9wG8AB4BfAAcAbwAGQI8ABQAAD66AAA/DwAAPxMAAD7pAAA+6QAAPyUAAD7lAAA+7AAAPuYAAD7iAAA+xAG8ACcBfAAgAPwAdQD8AI8A/ACPAHwAJAD8AHUDMAATAbwAHQE8ACABPAAgATwAIQE8ACEBPAAoATwAHgF8AC4Apz/mAbwALQC8ACkAAD7NAIMAGACDABgBhAAgAXwAEgH8ABcA/AANAXwADAG8ACkB/AAlAXwAHwG8ACICFQA+AXwAHwF8ABkBxAAqAYQAGwI8ABoBfAAvAUQAFwI8ABUBfABLATwAGQH8AC4BwwAkAYQADQH8AC8BvAA0AfwAFAC8ABICGAAqAbwAIAG8AC4A/AAXAfwAJAC8ABkA/AAiAXwAIAAAPuoAAAAYAAA/CgAAPvwAAD8gAAA+yAAAPycAAD7KAAA/AQAAPs4BPAAoAAA/NAG8ACkBvAAdAAA/NAAAPw8AAD7+AXwAMgF8ACEAfAAmALwALgC8AC4AvAARAPwAOAD8ADgAAD8vAXwAJwD8AEcCegATAPwAKgAAPtMBPAAYAMQ//AAAPqUAAD7mAAA/LwJ8ADkAhAAYAfwANAAAPqsAAD7BAAA+sgAAAAAAAD6sAAA+4wAAPv8AAD74AAA+xAAAPxIAAD7pAnwAIwJ8ACMAAD7wAPwAHQD8ACcAfAAfATwALQD8ACYBPAAjAAA/IQAAPt8AAD7wAfwAJwG8ACgBvAA/AbwAJAAAPpQB1gASAPwADgAAPrgBfAAfAAA+5AAAPtoBPAAyATwAMgD8ACMB+gA+ATwAIAE8AB4AAD7BAXwAMAF8AB4B/AAmALwAGgB8ABABfACGAPwAjwE8ACMBfAB0APwAJwD8ACYAvAAhAPwAJwAAPsABPAApATwAKQE8ABkAvAAaALwAGgC8ABoB/AAgAAA+wgAAPrsAAD8oATwAIgAAPvEB/AAvAbwADwG8ACwB/AAvAbwALAG8ACwBvAAsAbwAGAF8ADMBvAAxAbwAKgAAPsMBvAA9AAAAAAH8ABcBvAAaAjwAIAAAPsUBfAAgAAA/AwD8AA4AAD6tAXwAGAI8ACoAAD8JALwAMAAAPwwBPAATAiYAPgAAPukAAD8EAAA+yAAAPmAAAD5tAAA/DgAAPrsA/AA5AAA+0AAAPrUAAD7OAAA+wAAAPukAAD77AAA+lwAAPqEAAAAAAAA/lgAAPsICdQA+ALwAMQIyADYCcAA+AXwACQG8AA0CPAAoApwAPgI8ADACfAApATwAMAM8AEIB/AAsAjwAIQE8ABIBfAArArwAMgAAPxUCggA+ATwAHgIYACoAAD7FAbwAKwE8ACABfAAgALwAEwG6AC0BxAA0AAA+2gC8AE0CGAAqAbwAIAJ8AD0B/AAcAnAAPgH8ABcBrQAkAAA/DwAAPrUBPAA6ATwAIgE8ADcA/AAfAbwAKAE8ACYBPAAjAHwAGwI8ACYAAD7eAjwAIgAAPwEB/AAjATwAGAF8ABgBfAAvAAA/+AAAPmAAAD8SAAA/AwE8ABgBfAAbAcMAJAG8AB0AAD4wAAA+dQJ9ABUAvAAxALwANAC8ADQD6QAVAjwAGgH8ADwBvAApAAA/GwC8P/AB/AAmAbwAPAJ8ABkCfAAuAbwAKQI8ACsBvAApAXwAIAH8AD0C/AA2AbwAHAMzABUCAAAqATwAJgE8ACYAAAAMAzwAJQAAPu4B/AA4AAA+dQG8ADgBBD9mATwAMwF8ACAAAD7pALwAFwB8ACQCZAA2AbwAIAF/AAQApwA2AsoAHgIjAB4BvAAmALsAQgF8ABoCIwAqA5UAGALuABgBfAAUAi8AKgH1ACoBTgAqALwAJgAAPpUAAD7yAfwACwGaACQAAD7eAXwAJAG8ACEAAD6+AbwAKAAAPxoAAD7FAAA+sQAAPzAAAD3/AAA9+AAAPr8BfAAiAJwAMQHcABUBPAA8ATwAMwD8AB8AAD6qAXwAIAAAPscAAD6zAAA+6QAAPtwAAD7lAAA/DAAAPswAAD8tAXAAPgG8ABkAAD8GAAA+wQAAPskAAD5cALwAJwHgACgBugAxAeAAIgGMAD4AfAAbAPwAKQD8ADgAvAA2AAA+mAAAPxIAAAAAAAA+mAAAAAAAAD82AAA+eAAAPngAAD8PAb0APgAAAAAAAD82AAA+eAAAPngBPAAeAfo/7wH6P+8COAA+AYwAPgHEACIDCgA+A5AAPgOyAD4B3AASAaUAPgIYACoBvAA6AZUAPgGVAD4B/AA/Ab8APgIAACoBxAAiAcQAEwHMP/QCJAA+A6AAKgHMP/QBlT/vAcAANAIAACoBxAAiAdQAEgHUABICPAAsALoAPgH3AEMBlQA+AcQAEwHLAD4B5wAkApwAEwKcABMBwAA0AbcAEgG3ABIBtwASAbcAEgH3AEMCRgA+AdgAKgHtABIBiwA2AZoANgGNACQBmgAkAaQAJAG8ADwBtgA2AZgAGAGtADYBwwAkAX8AJAGcADYAuwA0AaQAJAGcADYCPAAmALs/hAGcADYCDgA2AUM/5gFcAB4BiQAkAXgAIAF4ABgBeAAYAgEAEgGUADYBmgAkAZoAJAGkACQBpAAkAUMANgF8AB4BlAA2AX0AJAFDADYBpAA2AaQANgGkADYBpAA2AakAGAF6ADYCEAA2AVwAHgJGAB4CRgAeAsAAAAKEADmChAA5guQAIgLkACIC5AAiAuQAIgKWABAClgAQAnwANwLQACmC0AApgtAAKYHgACIBfAAnATwAGAG6AC0A/AAvATwAJgB8AAgB9gASAXwACQD8AC8A/AAvAPwALwD8AC8A/AAvAAA/AwAAP70AAD8yAAA+zgAAPt4AAD7iAAA++gAAPvgAAD7HAAA+3gAAPuwAAD8JAAA+wQC8ADEBPAAyATwAPAE8ADcBPAAzAPwAHwD8AB8AvAAnALwAJwAAPuUAAD7PAAA++QAAPuAAAD8dAAA+6gAAPtIAwAAAAAAAAAD8AC4BfAANAAA+vgAAPsMAAD7JATwANQAAPuABPAA1AXwADQAAPr4BfAAhATwANwAAPw4AAD7AAAA+vgAAPr4AAD7BAXwAPQE8ADkAvAAxALwAOAAAPwoAABQAAkpAAAAAAAOAK4AAwABBAkAAABaAAAAAwABBAkAAQAKAFoAAwABBAkAAgAOAGQAAwABBAkAAwA4AHIAAwABBAkABAAaAKoAAwABBAkABQAaAMQAAwABBAkABgAaAN4AAwABBAkABwBUAPgAAwABBAkACAAIAUwAAwABBAkACQAgAVQAAwABBAkACwAgAXQAAwABBAkADAAgAZQAAwABBAkADQBYAbQAAwABBAkADgA0AgwAQwBvAHAAeQByAGkAZwBoAHQAIAAyADAAMQA3AC0AMgAwADEAOQAgAFQAaABlACAASQBuAHQAZQByACAAcAByAG8AagBlAGMAdAAgAGEAdQB0AGgAbwByAHMASQBuAHQAZQByAFIAZQBnAHUAbABhAHIASQBuAHQAZQByACAAUgBlAGcAdQBsAGEAcgA6ADIAMAAxADkAOgAyADAAYgAzADkAMgA4ADgAYQBJAG4AdABlAHIAIABSAGUAZwB1AGwAYQByADMALgAzADsAMgAwAGIAMwA5ADIAOAA4AGEASQBuAHQAZQByAC0AUgBlAGcAdQBsAGEAcgBJAG4AdABlAHIAIABVAEkAIABhAG4AZAAgAEkAbgB0AGUAcgAgAGkAcwAgAGEAIAB0AHIAYQBkAGUAbQBhAHIAawAgAG8AZgAgAHIAcwBtAHMALgByAHMAbQBzAFIAYQBzAG0AdQBzACAAQQBuAGQAZQByAHMAcwBvAG4AaAB0AHQAcABzADoALwAvAHIAcwBtAHMALgBtAGUALwBoAHQAdABwAHMAOgAvAC8AcgBzAG0AcwAuAG0AZQAvAE8ARgBMACAAMQAuADEAIAAoAFMASQBMACAATwBwAGUAbgAgAEYAbwBuAHQAIABMAGkAYwBlAG4AcwBlACwAIABWAGUAcgBzAGkAbwBuACAAMQAuADEAKQBoAHQAdABwADoALwAvAHMAYwByAGkAcAB0AHMALgBzAGkAbAAuAG8AcgBnAC8ATwBGAEwAAAADAAAAAAAA/jAAwAAAAAAAAAAAAAAAAAAAAAAAAAAA";

// Helper to convert Base64 to ArrayBuffer
function base64ToArrayBuffer(base64: string): ArrayBuffer {
  const binaryString = atob(base64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes.buffer;
}

// Function to fetch logo and convert to Data URI
async function getLogoDataUri(baseUrl: string): Promise<string> {
  const logoPath = "/images/BookShuttles.com-Logo.png";
  const absoluteLogoUrl = `${baseUrl}${logoPath}`;
  try {
    const response = await fetch(absoluteLogoUrl);
    if (!response.ok) {
      throw new Error(`Failed to fetch logo (${response.status}): ${absoluteLogoUrl}`);
    }
    const contentType = response.headers.get('content-type') || 'image/png'; // Default to png
    const buffer = await response.arrayBuffer();
    const base64 = Buffer.from(buffer).toString('base64');
    return `data:${contentType};base64,${base64}`;
  } catch (error) {
    console.error("Error fetching logo:", error);
    // Fallback or re-throw, depending on desired behavior
    // Returning an empty string or a placeholder might be options
    // For now, re-throwing to make the failure explicit
    throw new Error(`Could not get logo data URI: ${error instanceof Error ? error.message : String(error)}`);
  }
}


export async function GET(req: NextRequest) {
  try {
    const url = new URL(req.url);
    const { searchParams } = url;
    const baseUrl = url.origin; // e.g., http://localhost:3000 or https://bookshuttles.com

    // Get 'from' and 'to' query parameters
    const hasFrom = searchParams.has('from');
    const hasTo = searchParams.has('to');
    const from = hasFrom ? searchParams.get('from')?.slice(0, 100) : 'Your Location'; // Limit length
    const to = hasTo ? searchParams.get('to')?.slice(0, 100) : 'Your Destination'; // Limit length

    // Convert embedded font data and fetch logo data URI concurrently
    const [fontData, logoDataUri] = await Promise.all([
      Promise.resolve(base64ToArrayBuffer(interRegularOtfBase64)), // Convert Base64 font data
      getLogoDataUri(baseUrl) // Fetch logo data
    ]);

    // Define border style
    const borderThickness = 20; // Adjust thickness as needed
    const greenColor = '#004d3b';
    const textColor = greenColor; // Use green for text

    return new ImageResponse(
      (
        <div style={{
          background: 'white', // New background color
          color: textColor, // New text color
          width: '1200px',
          height: '630px',
          display: 'flex', // Main container uses flex
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
          fontFamily: '"Inter", sans-serif', // Use the loaded font
          padding: `${borderThickness}px`, // Padding equal to border thickness
          textAlign: 'center', // Center text
          border: `${borderThickness}px solid ${greenColor}`, // Thick green border
          boxSizing: 'border-box', // Ensure padding/border are included in width/height
          }}>
          {/* Use the logo Data URI - Increased size further */}
          <img src={logoDataUri} width={450} height={150} style={{ marginBottom: 30 }} alt="BookShuttles.com Logo" />
          {/* Route Text - Increased size */}
          {/* Added display:flex to satisfy Satori */}
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', fontSize: 72, fontWeight: 700, lineHeight: 1.2 }}>
            {from} → {to}
          </div>
          {/* Tagline - Increased size */}
           {/* Added display:flex to satisfy Satori */}
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', fontSize: 38, marginTop: 25, fontWeight: 500 }}>
            Shuttle Service · BookShuttles.com
          </div>
        </div>
      ),
      {
        width: 1200,
        height: 630,
        fonts: [
          {
            name: 'Inter',
            data: fontData, // Use the fetched font data
            style: 'normal',
            weight: 400, // Specify weight if needed
          },
        ],
      }
    );
  } catch (e: any) {
    console.error(`Failed to generate OG image: ${e.message}`);
    // Return a plain text error response or a fallback image response
    return new Response(`Failed to generate image`, {
      status: 500,
    });
  }
}
