name: Basic Workflow Test

on:
  push:
    branches: [ main ] # Trigger on push to main
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world from the test workflow!"
